version: '3'
services:
  app:
    build: .
    restart: unless-stopped
    network_mode: host
    environment:
      TM_USER: timemachine
      TM_PW: timemachine
      TM_SIZE: 1024000
    volumes:
      - '/mnt/usb-disk/timemachine:/timemachine'
      - '/etc/localtime:/etc/localtime:ro'
